# Generated by Django 3.1.3 on 2021-01-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team_1_name',
            new_name='team1Name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_1_score',
            new_name='team1Score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_2_name',
            new_name='team2Name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_2_score',
            new_name='team2Score',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='vice_cap',
            new_name='viceCap',
        ),
        migrations.RenameField(
            model_name='teammatches',
            old_name='no_result',
            new_name='noResult',
        ),
        migrations.RenameField(
            model_name='teammatches',
            old_name='total_matches',
            new_name='totalMatches',
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='locality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
