# Generated by Django 3.1.3 on 2021-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0002_auto_20210201_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
