# Generated by Django 3.1.3 on 2021-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0006_auto_20210205_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchDate',
            field=models.DateField(null=True),
        ),
    ]
