# Generated by Django 3.1.3 on 2021-02-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0007_auto_20210205_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team2Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
