# Generated by Django 3.1.3 on 2021-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0008_auto_20210205_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
