# Generated by Django 3.1.3 on 2021-02-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0009_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricketapp.team'),
        ),
    ]
