# Generated by Django 3.1.3 on 2021-02-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0010_auto_20210205_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1Name',
            new_name='team',
        ),
    ]
