# Generated by Django 3.1.3 on 2021-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0012_player_is_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_vcap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_cap',
            field=models.BooleanField(default=False),
        ),
    ]
