# Generated by Django 3.1.3 on 2021-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0013_auto_20210207_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='win',
            field=models.BooleanField(null=True),
        ),
    ]
