# Generated by Django 3.1.3 on 2021-02-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0014_auto_20210207_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100, null=True)),
                ('batsmanName', models.CharField(max_length=100, null=True)),
                ('batsmanRun', models.IntegerField(blank=True, null=True)),
                ('batsmanFours', models.IntegerField(blank=True, null=True)),
                ('batsmanSix', models.IntegerField(blank=True, null=True)),
                ('batsmanBalls', models.IntegerField(blank=True, null=True)),
                ('batsmanStrikeRate', models.FloatField(blank=True, null=True)),
                ('batsmanStatus', models.CharField(choices=[('Out', 'Out'), ('Not Out', 'Not Out')], max_length=100, null=True)),
                ('bowlerName', models.CharField(blank=True, max_length=100, null=True)),
                ('bowlerRun', models.IntegerField(blank=True, null=True)),
                ('bowlerMaidenOver', models.IntegerField(blank=True, null=True)),
                ('bowlerOvers', models.FloatField(blank=True, null=True)),
                ('bowlerEconomy', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricketapp.match')),
            ],
        ),
    ]
